### ISSUE TITLE
Element not found when launching some applications

### ISSUE THREAD

**Issue by dvesic** [eksime/VDesk#49]
Hello.

In some cases, when I launch an application on particular VD, VDesk reports error "Element not found":

![vdesk-element-not-found](https://user-images.githubusercontent.com/17367063/38018721-0066426a-3276-11e8-9573-934584bdc9f3.png)

For example, if I try to launch Viber with this:

"C:\Program Files (x86)\VDesk\VDesk.exe" on:2 noswitch:true  run:"C:\Users\dvesic\AppData\Local\Viber\Viber.exe" StartMinimized

it will report the error. If I remove Viber's "StartMinimized" parameter, it will launch it w/o error.

Strangely enough, even if there is no (visible) parameter in the command line for application, like this:

"C:\Program Files (x86)\VDesk\VDesk.exe" on:1 noswitch:true run:"C:\Program Files (x86)\Microsoft Office\root\office16\LYNC.EXE"

it will report the same error.

Regards,
Dejan

**Comment by Rimbaldo** [comment]
I agree with ChipRab. The same thing (COMM initialization error) happened to me. I had to take the noswitch:true on the command_line to make it work. Also updated to the last version!

**Comment by seanidzenga** [comment]
+1 This is occuring for me as well.

**Comment by eksime** [comment]
This issue should be fixed in 8c1bf48, try updating to version 1.2.0. This may be a little different to the other 1803-related errors, so if it remains an issue, then reopen.

**Comment by ZhangTianrong** [comment]
The problem seems to still exist in version 1.2.0. I am on Windows 10 1909.
